# Generated by Django 2.2.6 on 2020-05-21 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0070_remove_order_delivery_person'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Order Placed'), (2, 'Order Approved'), (3, 'Order Cancelled'), (4, 'Order Prepared'), (5, 'Order Picked Up'), (6, 'Order Delivered'), (7, 'Delivery Assigned'), (8, 'Delivery Rejected')], default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('extra_json', jsonfield.fields.JSONField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('event_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log', to='core.Order')),
                ('receipent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipent_log', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log', to='core.Restaurant')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
