# Generated by Django 2.2.6 on 2019-11-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='food',
            new_name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time_in_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
