# Generated by Django 2.2.6 on 2019-12-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20191120_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='core.Order'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
