# Generated by Django 2.2.6 on 2020-05-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_deliverytrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytrack',
            name='last_location_text',
        ),
    ]
