# Generated by Django 2.2.6 on 2020-05-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_remove_deliverytrack_last_location_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_time',
        ),
    ]
