# Generated by Django 2.2.6 on 2019-11-01 06:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('name_of_owner', models.CharField(max_length=255)),
                ('email_of_owner', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('registration_number', models.CharField(help_text='registration number of restaurant', max_length=255)),
                ('message', models.TextField(help_text='Explain in short why do you want to be registered here?')),
            ],
        ),
    ]
