# Generated by Django 2.2.6 on 2019-11-01 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_restaurantrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantrequest',
            name='requested_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 1, 7, 6, 32, 817713)),
        ),
    ]
