# Generated by Django 2.2.6 on 2019-11-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191101_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantrequest',
            name='requested_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
