# Generated by Django 2.2.6 on 2019-11-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191101_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantrequest',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
