# Generated by Django 2.2.6 on 2019-11-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_restaurant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/'),
        ),
    ]
