# Generated by Django 2.2.6 on 2019-11-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_foodmenu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
