# Generated by Django 2.2.6 on 2019-11-12 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_foodcart_mealtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='meal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu', to='core.MealType'),
        ),
    ]
