# Generated by Django 2.2.6 on 2019-11-13 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_restaurantmealtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantFoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restaurants', to='core.FoodCategory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_category', to='core.Restaurant')),
            ],
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='core.RestaurantFoodCategory'),
        ),
    ]
