# Generated by Django 2.2.6 on 2019-12-13 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191120_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantCuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurantmealtype',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='restaurantmealtype',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='foodmenu',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_charge',
            field=models.FloatField(blank=True, help_text='Delivery charges in dollars', null=True),
        ),
        migrations.DeleteModel(
            name='MealType',
        ),
        migrations.DeleteModel(
            name='RestaurantMealType',
        ),
        migrations.AddField(
            model_name='restaurantcuisine',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisines', to='core.Restaurant'),
        ),
    ]
