# Generated by Django 2.2.6 on 2019-12-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191213_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='location',
            new_name='location_point',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location_text',
            field=models.CharField(default='', max_length=500),
        ),
    ]
