# Generated by Django 2.2.6 on 2019-12-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20191214_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantimage',
            name='main_image',
            field=models.BooleanField(default=False, help_text='Make this your main image to be displayed?'),
        ),
    ]
