# Generated by Django 2.2.6 on 2019-12-18 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_restaurant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcart',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Restaurant'),
        ),
    ]
