# Generated by Django 2.2.6 on 2019-12-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_foodcart_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcustomize',
            name='calories',
            field=models.CharField(blank=True, help_text='calories contained in this ingredient(in cal)', max_length=100, null=True),
        ),
    ]
