# Generated by Django 2.2.6 on 2019-12-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_foodcustomize_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='foodmenu',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
