# Generated by Django 2.2.6 on 2019-12-25 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_auto_20191224_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcart',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='foodcart',
            name='modifier',
            field=models.ManyToManyField(related_name='orders', to='core.FoodCustomize'),
        ),
        migrations.AlterField(
            model_name='foodcart',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_added', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected'), (3, 'Prepared'), (4, 'Delivered')], null=True)),
                ('cart', models.ManyToManyField(related_name='order', to='core.FoodCart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
