# Generated by Django 2.2.6 on 2019-12-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20191225_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='last_added',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(blank=True, choices=[(1, 'On Delivery')], null=True),
        ),
    ]
