# Generated by Django 2.2.6 on 2019-12-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20191226_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcart',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
