# Generated by Django 2.2.6 on 2020-01-01 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_foodcart_checked_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantrequest',
            name='location_point',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
