# Generated by Django 2.2.6 on 2020-01-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200101_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_time',
            field=models.CharField(default='', max_length=200),
        ),
    ]
