# Generated by Django 2.2.6 on 2020-01-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_restaurant_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_cost',
            field=models.FloatField(default=0),
        ),
    ]
