# Generated by Django 2.2.6 on 2020-01-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_restaurant_delivery_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='delivery_cost',
        ),
    ]
