# Generated by Django 2.2.6 on 2020-01-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200108_0536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantrequest',
            old_name='location_text',
            new_name='state',
        ),
        migrations.AddField(
            model_name='restaurantrequest',
            name='does_your_restaurant_staff_deliver_order',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantrequest',
            name='street',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='restaurantrequest',
            name='town',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='restaurantrequest',
            name='zip_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
