# Generated by Django 2.2.6 on 2020-01-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200114_0538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='location_text',
            new_name='state',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='street',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='town',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='zip_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
