# Generated by Django 2.2.6 on 2020-01-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20200115_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_string',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
