# Generated by Django 2.2.6 on 2020-01-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_order_id_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
