# Generated by Django 2.2.6 on 2020-01-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_type',
            new_name='payment',
        ),
    ]
