# Generated by Django 2.2.6 on 2020-01-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_order_delivery_person'),
        ('core', '0043_auto_20200124_0822'),
    ]

    operations = [
    ]
