# Generated by Django 2.2.6 on 2020-01-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20200129_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_line2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
