# Generated by Django 2.2.6 on 2020-02-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20200129_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
