# Generated by Django 2.2.6 on 2020-02-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
