# Generated by Django 2.2.6 on 2020-02-14 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20200203_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_extra', models.CharField(help_text='Extra things that can come with the food', max_length=255)),
                ('cost', models.FloatField(blank=True, help_text='Cost of extras(in dollars)', null=True)),
                ('calories', models.CharField(blank=True, max_length=255, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='core.FoodMenu')),
            ],
        ),
        migrations.CreateModel(
            name='FoodStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_style', models.CharField(help_text='Style that comes with this food.', max_length=255)),
                ('cost', models.FloatField(blank=True, help_text='Cost of style(in dollars)', null=True)),
                ('calories', models.CharField(blank=True, help_text='calories contained in this ingredient(in cal)', max_length=100, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='core.FoodMenu')),
            ],
        ),
        migrations.RemoveField(
            model_name='foodcart',
            name='modifier',
        ),
        migrations.DeleteModel(
            name='FoodCustomize',
        ),
        migrations.AddField(
            model_name='foodcart',
            name='extras',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart', to='core.FoodExtra'),
        ),
        migrations.AddField(
            model_name='foodcart',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='core.FoodStyle'),
        ),
    ]
