# Generated by Django 2.2.6 on 2020-02-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20200214_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='extras',
            field=models.ManyToManyField(related_name='cart', to='core.FoodExtra'),
        ),
    ]
