# Generated by Django 2.2.6 on 2020-02-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20200214_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='old_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
