# Generated by Django 2.2.6 on 2020-02-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20200215_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodextra',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='foodmenu',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='foodstyle',
            name='calories',
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
