# Generated by Django 2.2.6 on 2020-02-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20200218_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
