# Generated by Django 2.2.6 on 2020-02-18 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20200218_0811'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodcart',
            unique_together=set(),
        ),
    ]
