# Generated by Django 2.2.6 on 2020-04-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20200402_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='preparation_time',
            field=models.IntegerField(null=True),
        ),
    ]
