# Generated by Django 2.2.6 on 2020-04-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20200403_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_time',
            field=models.IntegerField(default=0),
        ),
    ]
