# Generated by Django 2.2.6 on 2020-08-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_restaurantfoodcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
