# Generated by Django 2.2.6 on 2020-09-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20200907_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='chef_special',
            field=models.BooleanField(default=False),
        ),
    ]
