# Generated by Django 2.2.6 on 2020-05-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userlocationtrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocationtrack',
            name='last_location_text',
        ),
    ]
