# Generated by Django 2.2.6 on 2020-06-06 05:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_userlocationtrack_last_location_text'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userlocationtrack',
            managers=[
                ('geo_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
