# Generated by Django 2.2.6 on 2020-06-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200606_0514'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userlocationtrack',
            managers=[
            ],
        ),
    ]
