# Generated by Django 2.2.6 on 2020-06-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200606_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocationtrack',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlocationtrack',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
