# Generated by Django 2.2.6 on 2020-09-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_userfavourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavourite',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfavourite',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
